### PR TITLE
Fix #54 : "Add item to default page" modal form

### LINKED ISSUE #54: Menu "Add new... -> Add item to default page" does not work
In Plone 6.0.5 with plone.app.contentmenu 3.0.2,

- Add a new content type TTW in http://0.0.0.0:8080/Plone/@@dexterity-types named "Cover"
- Allow "File" and "Image" in "Contained items" field
- Check "Can be used as a default page" for the content type "Cover" in http://0.0.0.0:8080/Plone/@@content-controlpanel
- Create a content "Folder" in your site named "A folder"
- Create a content "Cover" in your folder named "My cover"
- Set "My cover" as default view in "Display" menu of "A folder"

When you want to add a new item ("File" or "Image") with the "Add new... -> Add item to default page" in "My cover" the modal form is not working.

The solution to this problem is to add an attribute data-pat-plone-modal="{"actionOptions": {"disableAjaxFormSubmit": True}" in the "a" tag of the "Add item to default page" link.

### PR DESCRIPTION
**Pull request by sverbois**

### CODE REVIEW

**Comment by sverbois** [comment]
@jenkins-plone-org please run jobs

**Comment by sverbois** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
I confirm that the problem exists, and that this PR fixes it.  Thanks!

**Comment by petschki** [comment]
does this need an upgrade step which sets default value to the registry?

**Comment by sverbois** [comment]
I don't think so, but I'm not aware of any link between the "Add item to default page" menu and the configuration register.

**Comment by mauritsvanrees** [comment]
Indeed no upgrade step needed.  This modal option is added on-the-fly.

**Pull request merged**
