### PR TITLE
display menu separator

### PR DESCRIPTION
**Pull request by mamico**
Attempt to fix https://github.com/plone/plone.app.layout/issues/321

### CODE REVIEW

**Comment by mamico** [comment]
@jenkins-plone-org please run jobs

**Review by petschki — CHANGES_REQUESTED** [review]
Thank you! This looks good and is much better, but I recommend adding the current seleted Item title to the top container view listing with this PR too. Then it would be perfect. See Plone 5:

Bildschirmfoto 2022-10-07 um 08 04 45

**Comment by mamico** [comment]
@jenkins-plone-org please run jobs

**Comment by mamico** [comment]
> Thank you! This looks good and is much better, but I recommend adding the current seleted Item title to the top container view listing with this PR too. Then it would be perfect. See Plone 5:

@petschki I get the point. Can you see if it’s okay now?

**Review by petschki — APPROVED** [review]
Perfect!

**Pull request merged**
