### PR TITLE
Put selected display on top, clean up separators for styling.

### PR DESCRIPTION
**Pull request by alecpm**

### CODE REVIEW

**Comment by jensens** [comment]
may you rebase

**Comment by alecpm** [comment]
Sure, I'll just remove the compile commit.

**Comment by alecpm** [comment]
I think this should also be considered for merge to Plone 5.0.x (i.e. 2.1.x branch of this package).

**Comment by alecpm** [comment]
This requires https://github.com/plone/Products.CMFPlone/pull/1812

**Pull request merged**
